In [11]:
import pandas as pd
import numpy as np
from datetime import datetime

In [12]:
df = pd.read_csv("store_sales_data (2).csv")
print("Original shape:", df.shape)
df.head()

Original shape: (100000, 25)

,Customer ID,Customer Name,Last Name,Date of Birth,Sales,Year,Outlet Type,City Type,Category of Goods,Region,...,Ship Date,Ship Mode,State,Postal Code,Product ID,Sub-Category,Product Name,Quantity,Discount,Profit
0,CUST000001,Curtis,Krause,1973-11-29,3344.69,2023,Large,Tier 1,Fast Food,East,...,2020-04-18,Same Day,West Bengal,700001,PROD000001,Burgers,Burgers - 718,3,0.09,448.24
1,CUST000002,Jeremy,Foster,1987-08-30,37094.41,2022,Medium,Tier 2,Fast Food,East,...,2021-01-11,Standard Class,Punjab,160001,PROD000002,Pizzas,Pizzas - 519,5,0.39,3134.34
2,CUST000003,Ariel,Mccann,1980-12-15,35501.08,2023,Large,Village,Electric Appliances,South,...,2020-08-16,Second Class,Gujarat,380001,PROD000003,Fans,Fans - 395,6,0.07,8324.21
3,CUST000004,Colleen,Maynard,1989-05-23,8969.33,2021,Medium,Village,Dairy Products,East,...,2021-10-16,First Class,West Bengal,700001,PROD000004,Milk,Milk - 798,4,0.18,1962.66
4,CUST000005,Gina,Holden,1957-12-31,35530.44,2021,Small,Village,Sessional Fruits & Vegetables,West,...,2019-01-25,Standard Class,Delhi,110001,PROD000005,Tomatoes,Tomatoes - 442,4,0.27,2843.93

In [13]:
date_cols = ["Date of Birth", "Sales Date", "Order Date", "Ship Date"]
for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors="coerce")
df.head()

,Customer ID,Customer Name,Last Name,Date of Birth,Sales,Year,Outlet Type,City Type,Category of Goods,Region,...,Ship Date,Ship Mode,State,Postal Code,Product ID,Sub-Category,Product Name,Quantity,Discount,Profit
0,CUST000001,Curtis,Krause,1973-11-29,3344.69,2023,Large,Tier 1,Fast Food,East,...,2020-04-18,Same Day,West Bengal,700001,PROD000001,Burgers,Burgers - 718,3,0.09,448.24
1,CUST000002,Jeremy,Foster,1987-08-30,37094.41,2022,Medium,Tier 2,Fast Food,East,...,2021-01-11,Standard Class,Punjab,160001,PROD000002,Pizzas,Pizzas - 519,5,0.39,3134.34
2,CUST000003,Ariel,Mccann,1980-12-15,35501.08,2023,Large,Village,Electric Appliances,South,...,2020-08-16,Second Class,Gujarat,380001,PROD000003,Fans,Fans - 395,6,0.07,8324.21
3,CUST000004,Colleen,Maynard,1989-05-23,8969.33,2021,Medium,Village,Dairy Products,East,...,2021-10-16,First Class,West Bengal,700001,PROD000004,Milk,Milk - 798,4,0.18,1962.66
4,CUST000005,Gina,Holden,1957-12-31,35530.44,2021,Small,Village,Sessional Fruits & Vegetables,West,...,2019-01-25,Standard Class,Delhi,110001,PROD000005,Tomatoes,Tomatoes - 442,4,0.27,2843.93

In [14]:
df["Order Year"] = df["Order Date"].dt.year
df["Order Month"] = df["Order Date"].dt.month
df["Order Month Name"] = df["Order Date"].dt.strftime("%B")
df["Order Quarter"] = df["Order Date"].dt.quarter
df["Order Quarter Name"] = "Q" + df["Order Quarter"].astype(str)
df["Order Weekday"] = df["Order Date"].dt.day_name()
df["Order YearMonth"] = df["Order Date"].dt.to_period("M").astype(str)

In [15]:
df["Customer Full Name"] = df["Customer Name"] + " " + df["Last Name"]

In [16]:
df["Age"] = 2026 - df["Date of Birth"].dt.year

In [17]:
df["Profit Margin %"] = (df["Profit"] / df["Sales"]).round(4)

In [18]:
df["Shipping Days"] = (df["Ship Date"] - df["Order Date"]).dt.days
df.columns = [c.strip().replace(" ", "_") for c in df.columns]

In [19]:
final_cols = [
    "Customer_ID", "Customer_Full_Name", "Age", "Segment",
    "Order_ID", "Order_Date", "Order_Year", "Order_Month", "Order_Month_Name",
    "Order_Quarter", "Order_Quarter_Name", "Order_Weekday", "Order_YearMonth",
    "Ship_Date", "Ship_Mode", "Shipping_Days",
    "Sales", "Quantity", "Discount", "Profit", "Profit_Margin_%",
    "Product_ID", "Product_Name", "Sub-Category", "Category_of_Goods",
    "Outlet_Type", "City_Type", "Region", "State", "Postal_Code"
]

In [20]:
df_clean = df[final_cols].copy()

In [21]:
df_clean.to_csv("store_sales_cleaned.csv", index=False)
df_clean.to_parquet("store_sales_cleaned.parquet", index=False)  # faster for Power BI

print("Cleaned shape:", df_clean.shape)
print("Saved: store_sales_cleaned.csv and store_sales_cleaned.parquet")
print(df_clean.head(3))

Cleaned shape: (100000, 30)
Saved: store_sales_cleaned.csv and store_sales_cleaned.parquet
  Customer_ID Customer_Full_Name  Age    Segment   Order_ID Order_Date  \
0  CUST000001      Curtis Krause   53   Consumer  ORD000001 2020-04-13
1  CUST000002      Jeremy Foster   39  Corporate  ORD000002 2021-01-08
2  CUST000003       Ariel Mccann   46   Consumer  ORD000003 2020-08-11

   Order_Year  Order_Month Order_Month_Name  Order_Quarter  ...  \
0        2020            4            April              2  ...
1        2021            1          January              1  ...
2        2020            8           August              3  ...

  Profit_Margin_%  Product_ID   Product_Name Sub-Category  \
0          0.1340  PROD000001  Burgers - 718      Burgers
1          0.0845  PROD000002   Pizzas - 519       Pizzas
2          0.2345  PROD000003     Fans - 395         Fans

     Category_of_Goods  Outlet_Type  City_Type  Region        State  \
0            Fast Food        Large     Tier 1    East  West Bengal
1            Fast Food       Medium     Tier 2    East       Punjab
2  Electric Appliances        Large    Village   South      Gujarat

   Postal_Code
0       700001
1       160001
2       380001

[3 rows x 30 columns]